id = "ntss"
name = "natyv Stylesheet"
description = "Syntax highlighting for natyv's .ntss stylesheet files."
version = "0.1.0"
schema_version = 1
authors = ["natyv"]
repository = "https://github.com/natyv/zed-ntss"

[grammars.ntss]
repository = "file:///Users/quinnmillican/Desktop/dev/natyv/editors/tree-sitter-ntss"
commit = "886798d86841b078438e324d26938dd500d356a7"
